In [1]:
# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier

In [2]:
#===============================================
# Task 1: Dataset Exploration and Understanding
#===============================================

# Define Column Name

column_names = [
'duration',
'protocol_type',
'service',
'flag',
'src_bytes',
'dst_bytes',
'land',
'wrong_fragment',
'urgent',
'hot',
'num_failed_logins',
'logged_in',
'num_compromised',
'root_shell',
'su_attempted',
'num_root',
'num_file_creations',
'num_shells',
'num_access_files',
'num_outbound_cmds',
'is_host_login',
'is_guest_login',
'count',
'srv_count',
'serror_rate',
'srv_serror_rate',
'rerror_rate',
'srv_rerror_rate',
'same_srv_rate',
'diff_srv_rate',
'srv_diff_host_rate',
'dst_host_count',
'dst_host_srv_count',
'dst_host_same_srv_rate',
'dst_host_diff_srv_rate',
'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate',
'dst_host_serror_rate',
'dst_host_srv_serror_rate',
'dst_host_rerror_rate',
'dst_host_srv_rerror_rate',
'attack',
'difficulty'
]

In [3]:
# Load Dataset

train = pd.read_csv(
    "dataset/KDDTrain+.txt",
    header=None,
    names=column_names)

test = pd.read_csv(
    "dataset/KDDTest+.txt",
    header=None,
    names=column_names)

In [4]:
# Dataset Summary

print("Training Dataset Shape :", train.shape)
print("Testing Dataset Shape :", test.shape)

print("\nNumber of Samples:")
print(train.shape[0])

print("\nNumber of Columns:")
print(train.shape[1])

print("\nNumber of Features:")
print(41)
print("\nExplanation: ")
print("The dataset contains 43 columns in total.")
print("Among them, 41 columns are network traffic features.")
print("1 column represents the attack label.")
print("1 column represents the difficulty level.")


print("\nFeature Names:")
print(column_names[:-2])

Training Dataset Shape : (125973, 43)
Testing Dataset Shape : (22544, 43)

Number of Samples:
125973

Number of Columns:
43

Number of Features:
41

Explanation:
The dataset contains 43 columns in total.
Among them, 41 columns are network traffic features.
1 column represents the attack label.
1 column represents the difficulty level.

Feature Names:
['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate']

In [5]:
# Dataset Preview

train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [6]:
# Dataset Information

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  object
 2   service                      125973 non-null  object
 3   flag                         125973 non-null  object
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   land                         125973 non-null  int64
 7   wrong_fragment               125973 non-null  int64
 8   urgent                       125973 non-null  int64
 9   hot                          125973 non-null  int64
 10  num_failed_logins            125973 non-null  int64
 11  logged_in                    125973 non-null  int64
 12  num_compromised              125973 non-null  int64
 13  root_shell                   125973 non-null  int64
 14  su_attempted                 125973 non-null  int64
 15  num_root                     125973 non-null  int64
 16  num_file_creations           125973 non-null  int64
 17  num_shells                   125973 non-null  int64
 18  num_access_files             125973 non-null  int64
 19  num_outbound_cmds            125973 non-null  int64
 20  is_host_login                125973 non-null  int64
 21  is_guest_login               125973 non-null  int64
 22  count                        125973 non-null  int64
 23  srv_count                    125973 non-null  int64
 24  serror_rate                  125973 non-null  float64
 25  srv_serror_rate              125973 non-null  float64
 26  rerror_rate                  125973 non-null  float64
 27  srv_rerror_rate              125973 non-null  float64
 28  same_srv_rate                125973 non-null  float64
 29  diff_srv_rate                125973 non-null  float64
 30  srv_diff_host_rate           125973 non-null  float64
 31  dst_host_count               125973 non-null  int64
 32  dst_host_srv_count           125973 non-null  int64
 33  dst_host_same_srv_rate       125973 non-null  float64
 34  dst_host_diff_srv_rate       125973 non-null  float64
 35  dst_host_same_src_port_rate  125973 non-null  float64
 36  dst_host_srv_diff_host_rate  125973 non-null  float64
 37  dst_host_serror_rate         125973 non-null  float64
 38  dst_host_srv_serror_rate     125973 non-null  float64
 39  dst_host_rerror_rate         125973 non-null  float64
 40  dst_host_srv_rerror_rate     125973 non-null  float64
 41  attack                       125973 non-null  object
 42  difficulty                   125973 non-null  int64
dtypes: float64(15), int64(24), object(4)
memory usage: 41.3+ MB

In [7]:
# Statistical Summary

train.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,difficulty
count,125973.00000,1.259730e+05,1.259730e+05,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,...,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000
mean,287.14465,4.556674e+04,1.977911e+04,0.000198,0.022687,0.000111,0.204409,0.001222,0.395736,0.279250,...,115.653005,0.521242,0.082951,0.148379,0.032542,0.284452,0.278485,0.118832,0.120240,19.504060
std,2604.51531,5.870331e+06,4.021269e+06,0.014086,0.253530,0.014366,2.149968,0.045239,0.489010,23.942042,...,110.702741,0.448949,0.188922,0.308997,0.112564,0.444784,0.445669,0.306557,0.319459,2.291503
min,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
50%,0.00000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000
75%,0.00000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,21.000000
max,42908.00000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,21.000000

In [8]:
# Identify Feature Types

categorical_features = [
    'protocol_type',
    'service',
    'flag']

numeric_features = [
    col for col in train.columns
    if col not in categorical_features
    and col not in ['attack', 'difficulty']]

print("Categorical Features:")
print(categorical_features)

print("\nNumeric Features:")
print(numeric_features)

print("\nNumber of Categorical Features:")
print(len(categorical_features))

print("\nNumber of Numeric Features:")
print(len(numeric_features))

Categorical Features:
['protocol_type', 'service', 'flag']

Numeric Features:
['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate']

Number of Categorical Features:
3

Number of Numeric Features:
38

In [9]:
# Analyze Class Distribution

class_distribution = train['attack'].value_counts()

print(class_distribution)

attack
normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: count, dtype: int64

In [ ]:
# Class Frequency Bar Chart

plt.figure(figsize=(12,6))

train['attack'].value_counts().plot(
    kind='bar')

plt.title('Attack Class Distribution')
plt.xlabel('Attack Type')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

In [ ]:
# duration Histogram

plt.figure(figsize=(8,5))

train['duration'].hist(
    bins=50)

plt.title('Distribution of Duration')
plt.xlabel('Duration')
plt.ylabel('Frequency')

plt.show()

In [ ]:
# src_bytes Box Plot

plt.figure(figsize=(8,5))

sns.boxplot(
    x=train['src_bytes'])

plt.title('Box Plot of src_bytes')
plt.xlabel('src_bytes')

plt.show()

In [ ]:
# srv_count Density Plot

plt.figure(figsize=(8,5))

sns.kdeplot(
    train['srv_count'],
    fill=True)

plt.title('Density Distribution of srv_count')
plt.xlabel('srv_count')
plt.ylabel('Density')

plt.show()

In [ ]:
# =======================================
#  TASK 2 & TASK 3:
#  DATA PREPROCESSING AND CLASSIFICATION
# =======================================

# Check Missing Values

print("Training Missing Values:",train.isnull().sum().sum())
print("Testing Missing Values:",test.isnull().sum().sum())

In [ ]:
# Check Duplicate Records

print("Train duplicates:", train.duplicated().sum())
print("Test duplicates:", test.duplicated().sum())

In [ ]:
# Remove Difficulty Column

train = train.drop(columns=['difficulty'])
test = test.drop(columns=['difficulty'])

In [ ]:
# Attack Mapping

attack_mapping = {

    'normal':'Normal',

    # DoS
    'apache2':'DoS',
    'back':'DoS',
    'land':'DoS',
    'neptune':'DoS',
    'mailbomb':'DoS',
    'pod':'DoS',
    'processtable':'DoS',
    'smurf':'DoS',
    'teardrop':'DoS',
    'udpstorm':'DoS',
    'worm':'DoS',

    # Probe
    'ipsweep':'Probe',
    'mscan':'Probe',
    'nmap':'Probe',
    'portsweep':'Probe',
    'saint':'Probe',
    'satan':'Probe',

    # R2L
    'ftp_write':'R2L',
    'guess_passwd':'R2L',
    'httptunnel':'R2L',
    'imap':'R2L',
    'multihop':'R2L',
    'named':'R2L',
    'phf':'R2L',
    'sendmail':'R2L',
    'snmpgetattack':'R2L',
    'snmpguess':'R2L',
    'spy':'R2L',
    'warezclient':'R2L',
    'warezmaster':'R2L',
    'xlock':'R2L',
    'xsnoop':'R2L',

    # U2R
    'buffer_overflow':'U2R',
    'loadmodule':'U2R',
    'perl':'U2R',
    'ps':'U2R',
    'rootkit':'U2R',
    'sqlattack':'U2R',
    'xterm':'U2R'
}

train['attack_multi'] = train['attack'].map(attack_mapping)
test['attack_multi'] = test['attack'].map(attack_mapping)

train['attack_binary'] = train['attack'].apply(lambda x: 'Normal' if x == 'normal' else 'Attack')
test['attack_binary'] = test['attack'].apply(lambda x: 'Normal' if x == 'normal' else 'Attack')

In [ ]:
# Split Development Data

train_dev, val_dev = train_test_split(
    train,
    test_size=0.2,
    random_state=42,
    stratify=train['attack_multi']
)

In [ ]:
# Separate Feature And Labels

X_train = train_dev.drop(
    ['attack', 'attack_binary', 'attack_multi'],
    axis=1
)

X_val = val_dev.drop(
    ['attack', 'attack_binary', 'attack_multi'],
    axis=1
)

X_test = test.drop(
    ['attack', 'attack_binary', 'attack_multi'],
    axis=1
)

y_train_binary = train_dev['attack_binary']
y_val_binary = val_dev['attack_binary']
y_test_binary = test['attack_binary']

y_train_multi = train_dev['attack_multi']
y_val_multi = val_dev['attack_multi']
y_test_multi = test['attack_multi']

In [ ]:
# Convert labels into machine-readable format

binary_encoder = LabelEncoder()

y_train_binary = binary_encoder.fit_transform(
    y_train_binary
)

y_val_binary = binary_encoder.transform(
    y_val_binary
)

y_test_binary = binary_encoder.transform(
    y_test_binary
)

multi_encoder = LabelEncoder()

y_train_multi = multi_encoder.fit_transform(
    y_train_multi
)

y_val_multi = multi_encoder.transform(
    y_val_multi
)

y_test_multi = multi_encoder.transform(
    y_test_multi
)

In [ ]:
# Encode Categorical Features

preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_features
        )
    ],
    remainder='passthrough'
)

X_train_encoded = preprocessor.fit_transform(X_train)
X_val_encoded = preprocessor.transform(X_val)
X_test_encoded = preprocessor.transform(X_test)

In [ ]:
# Scaling 

scaler = StandardScaler(with_mean=False)

X_train_scaled = scaler.fit_transform(X_train_encoded)
X_val_scaled = scaler.transform(X_val_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

In [ ]:
#======================================
# Task 4: Model Selection and Training
#======================================

# Random Forest - Binary Classification

rf_binary_results = []

for n in [50, 100, 200]:

    rf_binary = RandomForestClassifier(
        n_estimators=n,
        random_state=42,
        n_jobs=-1
    )

    rf_binary.fit(
        X_train_scaled,
        y_train_binary
    )

    val_pred = rf_binary.predict(
        X_val_scaled
    )

    val_acc = accuracy_score(
        y_val_binary,
        val_pred
    )

    rf_binary_results.append(
        [n, val_acc]
    )

    print(
        f"n_estimators={n}, Validation Accuracy={val_acc:.4f}"
    )

# Result Table

rf_binary_table = pd.DataFrame(
    rf_binary_results,
    columns=[
        "n_estimators",
        "Validation Accuracy"
    ]
)

print("\nResult Table: ")
print(rf_binary_table)

# Select Best Parameter

best_n_binary = max(
    rf_binary_results,
    key=lambda x: x[1]
)[0]

print(
    "\nBest n_estimators:",
    best_n_binary
)

# Train Final RF Binary Model

rf_binary_final = RandomForestClassifier(
    n_estimators=best_n_binary,
    random_state=42,
    n_jobs=-1
)

rf_binary_final.fit(
    X_train_scaled,
    y_train_binary
)

# Validation Classification Report

val_pred_binary = rf_binary_final.predict(
    X_val_scaled
)

print("\nClassification report: ")
print(
    classification_report(
        y_val_binary,
        val_pred_binary
    )
)

In [ ]:
# Random Forest - Multiclass Classification

rf_multi_results = []

for n in [50, 100, 200]:

    rf_multi = RandomForestClassifier(
        n_estimators=n,
        random_state=42,
        n_jobs=-1
    )

    rf_multi.fit(
        X_train_scaled,
        y_train_multi
    )

    val_pred = rf_multi.predict(
        X_val_scaled
    )

    val_acc = accuracy_score(
        y_val_multi,
        val_pred
    )

    rf_multi_results.append(
        [n, val_acc]
    )

    print(
        f"n_estimators={n}, Validation Accuracy={val_acc:.4f}"
    )

# Result Table

rf_multi_table = pd.DataFrame(
    rf_multi_results,
    columns=[
        "n_estimators",
        "Validation Accuracy"
    ]
)

print("\nResult Table: ")
print(rf_multi_table)

# Select Best Parameter

best_n_multi = max(
    rf_multi_results,
    key=lambda x: x[1]
)[0]

print(
    "\nBest n_estimators:",
    best_n_multi
)

# Train Final RF Binary Model

rf_multi_final = RandomForestClassifier(
    n_estimators=best_n_multi,
    random_state=42,
    n_jobs=-1
)

rf_multi_final.fit(
    X_train_scaled,
    y_train_multi
)

# Validation Classification Report

val_pred_multi = rf_multi_final.predict(
    X_val_scaled
)

print("\nClassification report: ")
print(
    classification_report(
        y_val_multi,
        val_pred_multi
    )
)

In [ ]:
# MLP - Binary Classification

mlp_binary_results = []

for hidden in [

    (50,),
    (100,),
    (100,50)

]:

    mlp_binary = MLPClassifier(
        hidden_layer_sizes=hidden,
        max_iter=30,
        random_state=42
    )

    mlp_binary.fit(
        X_train_scaled,
        y_train_binary
    )

    val_pred = mlp_binary.predict(
        X_val_scaled
    )

    val_acc = accuracy_score(
        y_val_binary,
        val_pred
    )

    mlp_binary_results.append(
        [hidden, val_acc]
    )

    print(
        f"{hidden} -> {val_acc:.4f}"
    )

mlp_binary_table = pd.DataFrame(
    mlp_binary_results,
    columns=[
        "hidden_layer_sizes",
        "Validation Accuracy"
    ]
)

print("\nResult Table: ")
print(mlp_binary_table)

best_hidden_binary = max(
    mlp_binary_results,
    key=lambda x: x[1]
)[0]

print(
    "\nBest Hidden Layer:",
    best_hidden_binary
)

mlp_binary_final = MLPClassifier(
    hidden_layer_sizes=best_hidden_binary,
    max_iter=30,
    random_state=42
)

mlp_binary_final.fit(
    X_train_scaled,
    y_train_binary
)

val_pred_binary = mlp_binary_final.predict(
    X_val_scaled
)

print("\nClassification Report: ")
print(
    classification_report(
        y_val_binary,
        val_pred_binary
    )
)

In [ ]:
# MLP - Multiclass Classification

mlp_multi_results = []

for hidden in [

    (50,),
    (100,),
    (100,50)

]:

    mlp_multi = MLPClassifier(
        hidden_layer_sizes=hidden,
        max_iter=30,
        random_state=42
    )

    mlp_multi.fit(
        X_train_scaled,
        y_train_multi
    )

    val_pred = mlp_multi.predict(
        X_val_scaled
    )

    val_acc = accuracy_score(
        y_val_multi,
        val_pred
    )

    mlp_multi_results.append(
        [hidden, val_acc]
    )

    print(
        f"{hidden} -> {val_acc:.4f}"
    )

    mlp_multi_table = pd.DataFrame(
    mlp_multi_results,
    columns=[
        "hidden_layer_sizes",
        "Validation Accuracy"
    ]
)

print("\nResult Table:")
print(mlp_multi_table)

best_hidden_multi = max(
    mlp_multi_results,
    key=lambda x: x[1]
)[0]

print(
    "\nBest Hidden Layer:",
    best_hidden_multi
)

mlp_multi_final = MLPClassifier(
    hidden_layer_sizes=best_hidden_multi,
    max_iter=30,
    random_state=42
)

mlp_multi_final.fit(
    X_train_scaled,
    y_train_multi
)

val_pred_multi = mlp_multi_final.predict(
    X_val_scaled
)

print("\nClassification Report:")
print(
    classification_report(
        y_val_multi,
        val_pred_multi
    )
)